sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - BUCKET=akerl-go-deadmanswitch
script: make
deploy:
  provider: script
  script:
  - make release || travis_terminate 1
  - aws s3 cp pkg/payload.zip "s3://$BUCKET/lambdas/payload-$TRAVIS_TAG.zip" || travis_terminate
    1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    rooms:
      secure: JRAwk4uIGnqCSzoAjGXAAq7iJMRwbYUwMTe2FHzNQDgyiWAze+OqHqiN+wZFncRcOMESGbQtaU7GiqVYqsEczP7nagVKKb+yf0hVYc10nqy3Alz2Wx5VK5TPUKMI9SbzONIushp59aIebpaGYanvWMDG9rRSFiEGwMZiZZZyxYxbQxzefNu+txRUUC3CVcJYVYIMZ5eOn8LwYx9JA7earnhtAET+9Gw+Di4YuVZgUbB931gjLcuvZV9hFuDo9R8iie5QhVJZ5vlI2xbxnrmu3UGwPb4jPw4AZkMXlas9rwsssEzgIrAkTOZKqM6itdjZ3HOJR0DueDl/o4AVmKKSvl5BA7p50PNQ/nWu5QvCrulGzbVwqbdE/7xIm3UYbUsy12lX5w7ZmsqcRnAJTwcuZ2e77mdv7SVuKl49zj/5lyNDKn64zU/IcxK7PkqU8JibT1RyNCuP62wrPwlK6GZWY+k32UkObjU7NwDm1SWYtyiYFZuex8+wU9SH3ZxFigmo9jLxvrgM8LGsho4mkOer0wKYciFY8WAgz1ZJxBcETzKh3QPSndZeqZWNlWjIhHZPqSsMZ/j3IQFgetG3rtMYF9Byfi1ErIX6YGvCqxs617ex78WFzCU6gYeeznmU0FaFINTBJuPmhbjS8txybb5qhIA7U5dsz4jiJm4GipQloAk=
